### ISSUE TITLE
Umbrella vNext: `next` version of Themes

### ISSUE THREAD

**Issue by LekoArts** [LekoArts/gatsby-themes#570]
## Overview

This will be the central place for the `vNext` project or in other words: All themes will receive a major version bump. I want to make some breaking changes to the themes that overall will benefit the themes (ease of use, performance, similarity).

I'll merge the work into a `next` branch.

## Work

- [x] Replace `gatsby-image` with the new `gatsby-plugin-image`
- [x] Use `lessBabel` option for `gatsby-plugin-mdx`
- [x] Remove `gatsby-plugin-typescript`
- [x] Bump min. Gatsby version for `peerDep`
- [x] Use `gatsby-omni-font-loader` instead of `typefaces`
- [x] Use latest version of Theme UI (on `next` tag)
- [x] Update TS types
- [x] Update packages to latest versions (e.g. next Emotion major)
	- [x] Remove `@emotion/styled` wherever possible
- [ ] ~~Create `docs` folder in repo~~
	- [ ] ~~Create short guide about modifying Theme UI stuff~~

### Motivation

- The new image plugin has better performance, more options and will be the path formward
- Adding `lessBabel` is speeding up the build a lot but breaks some things. People will sometimes need to set it to `false` => ~~**Document way on how to override `gatsby-plugin-mdx` in a `/docs` folder and reference this in theme README (instead of repeating myself)**~~
- ~~Same names for similar options across themes makes it easier to understand their options~~
- TypeScript plugin is included by default in newer versions of Gatsby
- The font loader is more performant than typefaces
- Theme UI will reach 1.0 in the _nearer_ future, so already upgrading to the `next` tag now (which is more or less stable from my experience) is making the switch then easier

**Comment by LekoArts** [comment]
Status update: I have something WIP but I waited for some upstream fixes (in `gatsby` and other packages) so that the vNext release is working great for everyone. I'll now be able to push more on this upgrade here.

**Comment by LekoArts** [comment]
Half of the themes is done (see progress at https://github.com/LekoArts/gatsby-themes/tree/next)

**Comment by LekoArts** [comment]
Fixed by https://github.com/LekoArts/gatsby-themes/pull/599
